import React from 'react';
import { FaCaretDown } from "react-icons/fa";

const Questions = () => {
  return (
    <section className='question bg-[#0A0B0E] lg:py-[120px] md:py-[80px] py-[80px]'>
        <div className="container_custom xl:w-[1440px] lg:px-[80px] mx-auto md:px-[40px] xsm:px-[45px] px-[20px]">
            <div className="con lg:flex justify-center lg:text-left text-center gap-16">
                <div className="p_1 lg:w-[476px] w-[100%]">
                    <h2 className='text_sp md:text-[46px] text-[30px] font-semibold mb-[18px]'>Have questions?
                    <br />We have answers!</h2>
                    <p className='text-[#B6B6B7] mb-6'>Want to know more? You can email us anytime atsupport@imagine.com</p>
                    <button className='border-0'>
                        <a href="" className='text-white py-[12px] px-6 block bg-[#8850FF] rounded-[10px] text-[16px] font-semibold'>Launch App</a>
                    </button>
                </div>
                <div className="p_2 lg:mt-0 mt-16">
                    <div className="acc_container">
                        <div className="main_box">
                            <div className="sub_box bg-[#121317] mb-6 xl:w-[676px] lg:w-[408px] w-full rounded-[14px] p-5 flex text-white justify-between items-center md:text-[16px] text-[14px]"><span className='text-left'>What is Imagine? </span><FaCaretDown /></div>
                        </div>
                        <div className="main_box">
                            <div className="sub_box bg-[#121317] mb-6 xl:w-[676px] lg:w-[408px] w-full rounded-[14px] p-5 flex text-white justify-between items-center md:text-[16px] text-[14px]"><span className='text-left'>Can I use the images generated by the platform for commercial purposes?
                            </span><FaCaretDown /></div>
                        </div>
                        <div className="main_box">
                            <div className="sub_box bg-[#121317] mb-6 xl:w-[676px] lg:w-[408px] w-full rounded-[14px] p-5 flex text-white justify-between items-center md:text-[16px] text-[14px]"><span className='text-left'>What payment options are available?
                            </span><FaCaretDown /></div>
                        </div>
                        <div className="main_box">
                            <div className="sub_box bg-[#121317] mb-6 xl:w-[676px] lg:w-[408px] w-full rounded-[14px] p-5 flex text-white justify-between items-center md:text-[16px] text-[14px]"><span className='text-left'>Is there a free trial?
                            </span><FaCaretDown /></div>
                        </div>
                        <div className="main_box">
                            <div className="sub_box bg-[#121317] mb-6 xl:w-[676px] lg:w-[408px] w-full rounded-[14px] p-5 flex text-white justify-between items-center md:text-[16px] text-[14px]"><span className='text-left'>Can I cancel my Plan? </span><FaCaretDown /></div>
                        </div>
                        <div className="main_box">
                            <div className="sub_box bg-[#121317] mb-6 xl:w-[676px] lg:w-[408px] w-full rounded-[14px] p-5 flex text-white justify-between items-center md:text-[16px] text-[14px]"><span className='text-left'>Can I upgrade or downgrade my current plan? </span><FaCaretDown /></div>
                        </div>
                        <div className="main_box">
                            <div className="sub_box bg-[#121317] mb-6 xl:w-[676px] lg:w-[408px] w-full rounded-[14px] p-5 flex text-white justify-between items-center md:text-[16px] text-[14px]"><span className='text-left'>What is Imagine's refund policy? </span><FaCaretDown /></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
  )
}

export default Questions;